config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  resource :session, controller: "clearance/sessions", only: [:create]

  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:create, :edit, :update]
  end

  get "/sign_in" => "clearance/sessions#new", as: "sign_in"
  delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up" => "clearance/users#new", as: "sign_up"
  resources :incomes, only: [:create]
  resources :expenses, only: [:create]
  root 'cashflows#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_detail.rb
class BankDetail < ApplicationRecord
  belongs_to :contact
end

app/models/cashflow.rb
class Cashflow < ApplicationRecord
  class << self
    def frequencies
      ["monthly", "one-off"]
    end
  end

  belongs_to :user

  validates :amount, presence: true
  validates :title, presence: true
  validates :billed_on, presence: true

  has_one_attached :document

  before_create :set_reimbursed

  def set_reimbursed
    if paid_by && paid_by.downcase == "sheng"
      self.reimbursed = false
    end
  end

end

app/models/contact.rb
class Contact < ApplicationRecord
  has_many :bank_details
end

app/models/expense.rb
class Expense < Cashflow

end

app/models/income.rb
class Income < Cashflow

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User

  has_many :expenses
  has_many :incomes
  has_many :contacts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
end

app/controllers/cashflows_controller.rb
class CashflowsController < ApplicationController
  before_action :require_login

  def index
    @expenses = current_user.expenses
    @incomes = current_user.incomes
    @expense = Expense.new
    @income = Income.new
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :require_login

  def create
    @expense = current_user.expenses.new(expense_params)
    if @expense.save
      redirect_to root_path
    else
      flash.now[:error] = @expense.errors.full_messages
      render "expenses/new"
      # @expenses = current_user.expenses
      # @incomes = current_user.incomes
    end
  end

  private

  def expense_params
    params.require(:expense).permit(:title, :category, :amount, :frequency, :start_date, :end_date, :description, :billed_on, :document, :paid_by)
  end
end

app/controllers/incomes_controller.rb
class IncomesController < ApplicationController
  before_action :require_login

  def create
    @income = current_user.incomes.new(income_params)
    if @income.save
      redirect_to cashflows_path
    end
  end

  private

  def income_params
    params.require(:cashflow).permit(:name, :frequency, :amount, :start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/expenses_helper.rb
module ExpensesHelper
end

app/views/cashflows/create.html.erb
<h1>Expenses#create</h1>
<p>Find me in app/views/expenses/create.html.erb</p>

app/views/cashflows/index.html.slim
.columns.is-centered
  .column.is-3.has-text-centered
    h1 Cashflow

.columns
  .column
    section.cashflow-details
      section.expenses-details.details
        h3.title.has-text-centered Expenses
        table.table.is-striped#expenses
          thead
            th Title
            th Description
            th Category
            th Amount
            th Paid By
            th Billed On
            th Reimbursed
            / th Document
          tbody
            - @expenses.each do |expense|
              tr
                td
                  - if expense.document.attached?
                    = link_to expense.title, expense.document
                  - else
                    = expense.title
                td = expense.description
                td = expense.category
                td = expense.amount
                td = expense.paid_by
                td = expense.billed_on
                td = expense.reimbursed
                / - if expense.document.attached?
                  td = link_to "Document", expense.document
      / section.income-details.details
        h3.title.has-text-centered Income
        table.table.is-striped
          thead
            th Name
            th Amount
            th Date
          tbody
          - @incomes.each do |expense|
            td = expense.name
            td = expense.amount
            td = expense.created_at.to_date

.columns.is-centered
  .column.is-centered.is-two-fifths
    .toggle-form-buttons.column
      a.button.is-danger.toggle-form data-toggle-form="expense-form" Add an Expense
      / a.button.is-primary.toggle-form data-toggle-form="income-form" Add an Income
    .section-forms.column
      #expense-form.form
        h3.has-text-centered Create Expense
        = form_for @expense do |f|
          .field
            = f.label :title, class: 'label'
            .control
              = f.text_field :title, class: 'input', placeholder: 'Ttile'
          .field
            = f.label :description, class: 'label'
            .control
              = f.text_field :description, class: 'input', placeholder: 'Description'
          .field
            = f.label :category, class: 'label'
            .control
              = f.text_field :category, class: 'input', placeholder: 'Description'
          .field
            = f.label :amount, class: 'label'
            .control
              = f.number_field :amount, step: :any, class: 'input', placeholder: 'Amount', step: :any
          .field
            = f.label :paid_by, class: 'label'
            .control
              = f.select :paid_by, options_for_select([["Dad", "dad"],["Sheng", "sheng"]]), class: 'input'
          .field
            = f.label :billed_on, class: 'label'
            .control
              = f.date_field :billed_on, class: 'input'
          .field
            = f.label :document, class: 'label'
            .control
              = f.file_field :document, class: ''
          / .file.has-name.field
          /   = f.label :document, class: 'label'
          /   label.file-label.control
          /     = f.file_field :document, class: 'file-input'
          /     span.file-cta
          /       span.file-icon
          /         i.fas.fa-upload
          /       span.file-label Choose a file
          /     span.file-name
          / .field
            = f.label :frequency, class: 'label'
            .control.select
              = f.select :frequency, Cashflow.frequencies, class: 'input', placeholder: 'Frequency'
          / .field
            = f.label :start_date, class: 'label'
            .control
              = f.date_field :start_date, class: 'input'
          / .field
            = f.label :end_date, class: 'label'
            .control
              = f.date_field :end_date, class: 'input'
          .field
            .control
              = f.submit "Create Expense", class: "button is-pimary"

      / #income-form.form
        h3.has-text-centered Create Income
        = form_for @income do |f|
          .field
            = f.label :name, class: 'label'
            .control
              = f.text_field :name, class: 'input', placeholder: 'Name'
          .field.is-horizontal
            .field-label
              = f.label :amount, class: 'label'
            .field-body
              .field.is-grouped
                .control
                  = f.number_field :amount, step: :any, class: 'input', placeholder: 'Amount', step: 0.01
                / = f.label :frequency, class: 'label'
                .control.select
                  = f.select :frequency, Cashflow.frequencies, class: 'input', placeholder: 'Frequency'
          .field.is-horizontal
            .field-label
              = f.label :start_date, class: 'label'
            .field-body
              .field.is-grouped
                .control
                  = f.date_field :start_date, class: 'input'
                / label.label.field-label = f.label :end_date
                .control
                  = f.date_field :end_date, class: 'input'
          .field
            .control
              = f.submit "Create Income", class: "button is-pimary"

app/views/expenses/_form.slim
.field
  = f.label :title, class: 'label'
  .control
    = f.text_field :title, class: 'input', placeholder: 'Ttile'
.field
  = f.label :description, class: 'label'
  .control
    = f.text_field :description, class: 'input', placeholder: 'Description'
.field
  = f.label :category, class: 'label'
  .control
    = f.text_field :category, class: 'input', placeholder: 'Description'
.field
  = f.label :amount, class: 'label'
  .control
    = f.number_field :amount, step: :any, class: 'input', placeholder: 'Amount', step: :any
.field
  = f.label :paid_by, class: 'label'
  .control
    = f.select :paid_by, options_for_select([["Dad", "dad"],["Sheng", "sheng"]]), class: 'input'
.field
  = f.label :billed_on, class: 'label'
  .control
    = f.date_field :billed_on, class: 'input'
.field
  = f.label :document, class: 'label'
  .control
    = f.file_field :document, class: ''
.field
  .control
    = f.submit "Create Expense", class: "button is-pimary"

app/views/expenses/new.html.slim
.columns.is-centered
  .column.is-3.has-text-centered
    = form_for @expense do |f|
      = render partial: "form", locals: { f: f}

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta content=("text/html; charset=UTF-8") http-equiv="Content-Type">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= csrf_meta_tag %>
  <link href='https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.1/css/bulma.css' rel="stylesheet">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body>
  <nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <%= link_to "Cashflow Tracker", root_path, class: "navbar-item" %>
      <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbar">
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
        <span aria-hidden="true"></span>
      </a>
    </div>
    <div class="navbar-menu" id="navbar">
      <div class="navbar-start"></div>
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            <% if signed_in? -%>
              <%= button_to t(".sign_out"), sign_out_path, method: :delete, class: "button is-primary" %>
            <% else -%>
              <%= link_to t(".sign_in"), sign_in_path, class: "button is-primary" %>
            <% end -%>
          </div>
        </div>
      </div>
    </div>
  </nav>

  <div id="flash">
    <% flash.each do |key, value| -%>
      <div id="notification flash_<%= key %>">
        <button class="delete"></button>
        <%= value %>
      </div>
    <% end %>
  </div>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<div class="text-field field">
  <%= form.label :email , class: "label" %>
  <div class="control">
    <%= form.text_field :email, type: 'email' , class: "input" %>
  </div>
</div>

<div class="password-field field">
  <%= form.label :password , class: "label" %>
  <div class="control">
    <%= form.password_field :password , class: "input" %>
  </div>
</div>

app/views/users/new.html.erb
<div class="columns is-centered is-mobile">
  <div id="clearance" class="sign-up column is-four-fifths">
    <h1 class="has-text-centered"><%= t(".title") %></h1>

    <%= form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>

      <div class="submit-field field">
        <div class="field">
          <div class="control">
            <%= form.submit "Sign Up", class: "button is-primary" %>
          </div>
        </div>
      </div>

      <div class="other-links field submit-field">
        <div class="field">
          <div class="control">
            <%= link_to t(".sign_in"), sign_in_path, class: "button" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>